### ISSUE TITLE
Not working in Atom version 0.209

### ISSUE THREAD

**Issue by mok0** [olmokramer/atom-block-cursor#21] opened 2015-06-13 17:48 UTC
It appears that block-cursor stopped working after I upgraded Atom to version 0.209. Now I have no cursor at all. When I disable block-cursor I get the standard I-beam cursor :-(

**Comment by mok0** [comment] 2015-06-13 17:50
Duplicate of issue #20.

**Comment by olmokramer** [comment] 2015-06-13 18:33
Yes indeed duplicate of #20. I'll be closing this one and continue discussion over there. Thanks for the report though :)

**Closed as completed by olmokramer** 2015-06-13 18:33 UTC
